# Generated by Django 4.2.4 on 2023-08-31 14:19

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_article_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=mdeditor.fields.MDTextField(),
        ),
    ]
